import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="fixed top-0 left-0 right-0 z-50 w-full px-12 py-4 bg-black/30 backdrop-blur">
          <h1 className="text-xl text-white font-bold tracking-tight">
            <span className="text-blue-500">Wind</span>
            Press
          </h1>
        </header>
        <main className="text-white pt-20 px-12">{children}</main>
      </body>
    </html>
  );
}
