import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full bg-black px-12 py-4 flex flex-row justify-between">
          <h1 className="text-xl text-white font-semibold tracking-tight">
            <span className="text-blue-500">Wind</span>
            Press
          </h1>
        </header>

        {children}
      </body>
    </html>
  );
}
